line-length = 100
target-version = "py311"

[format]
# Format settings 

[lint]
select = ["E", "F", "W", "I"]
fixable = ["ALL"]

[lint.per-file-ignores]
"__init__.py" = ["F401"]
"tests/**" = ["F841"]
